#!/usr/bin/env bash
# Jules environment setup for landing-page-starter.
#
# Paste this into the Jules web app: select the repo -> Configuration ->
# Environment setup script. Then press Validate, then Run and Snapshot, so every
# future session starts from an identical known-good baseline instead of
# re-deriving one and getting it slightly different each time.
#
# It must stay fast and it must fail loudly. A setup that half-works produces a
# session that spends its budget repairing the toolchain instead of doing the
# task — which is exactly the failure this repo has already paid for once.

set -euo pipefail

echo "node: $(node -v)"

corepack enable
corepack prepare pnpm@10.30.3 --activate
echo "pnpm: $(pnpm -v)"

# --frozen-lockfile is not optional. The lockfile is the pinned dependency set;
# resolving fresh is how a session ends up "helpfully" upgrading the toolchain.
pnpm install --frozen-lockfile

# next-env.d.ts is gitignored and generated by the Next build. Generate it now
# so `pnpm run typecheck` works standalone.
pnpm exec next build --no-lint >/dev/null 2>&1 || pnpm run build

# Fail at setup with a clear message rather than mid-task with a confusing one.
pnpm run typecheck
pnpm run lint
pnpm run check:conventions

echo "environment ready — 'pnpm run verify' is the definition of done"
